### ISSUE TITLE
Curse word followed by a comma was missed in the censor

### ISSUE THREAD

**Issue by Imveryweird** [jdanders/calibre-plugin-language-cleaner#1]
![20200828_064503](https://user-images.githubusercontent.com/66542108/91557432-13cea800-e8fa-11ea-957d-c01d3f53ae41.jpg)
Edit: Turns out to either be a limit or inability to censor stuff.

**Comment by jdanders** [comment]
Turns out "hell" is one of the trickier words to clean up. My intent was that the source material stay as readable as possible, and there are many non-profane uses of the word (see "The Bible" for examples). Without more context I can't tell if this was a real miss or something that is appropriate. Can you include the whole sentence?

> Edit: Turns out to either be a limit or inability to censor stuff.

Does your edit comment mean you have been unable to get it to work at all?

**Comment by Imveryweird** [comment]
It works but not well. Like, a transformer fan fiction completely missed an italic and all caps S***! Three times. I'm not going to use this on the bible. Nor do I care if the context doesn't deserve a heck. I'd like an option to do a full censor, regardless of context at least. It censored a few to heck and some to crap but not a lot.

**Comment by Imveryweird** [comment]
I was completely unable to censor an all caps and italics S***!

**Comment by Imveryweird** [comment]
I was completely unable to censor an all caps and italics S***! At least give the option to censor regardless of context.

**Comment by Imveryweird** [comment]
![Screenshot_20200830-161725_Google Play Books](https://user-images.githubusercontent.com/66542108/91669701-84351f00-eadc-11ea-9ae0-0d372f8d8e9f.jpg)
That is the full sentence.

**Comment by jdanders** [comment]
> It works but not well. Like, a transformer fan fiction completely missed an italic and all caps S***! Three times. 

The only way that got through was if there's something in the ebook source that broke up the word. EPUBs have formatting tags that aren't displayed,so if it was something like `<italic>S</italic>H**!` then the filter would miss that. In order to debug that, I would need a copy of the source file. Or, if you "edit" the ebook in calibre, you can see what the source text actually looks like and just paste that.

> I'm not going to use this on the bible. Nor do I care if the context doesn't deserve a heck. I'd like an option to do a full censor, regardless of context at least. It censored a few to heck and some to crap but not a lot.

There are lots of options for a dumb filter, the simplest being the search and replace feature built into Calibre.

> That is the full sentence

That must be something in the source file that is weird. If I run this through the filter:

```
 "had.  Hell, J'k had"
```

I get this result

```
 "had.  Heck, J'k had"
```

**Comment by jdanders** [comment]
Feel free to open again if you can provide more details on the actual source formatting of the books in question.
